# Generated by Django 6.1.1 on 2026-09-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Fan', 'Fan'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop'), ('TV', 'TV'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
